version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/split
      SPRING_DATASOURCE_USERNAME: 1373
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: postgres_container
    environment:
      POSTGRES_DB: split
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1373
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
